version: '3.8'
services:
  api:
    build:
      dockerfile: dockerfile
      context: ./server
      target: prod
    ports:
      - '5000:5000'
  client:
    build:
      dockerfile: dockerfile
      context: ./client
      target: prod
    ports:
      - '3000:80'
