# Development specific setup
FROM node:22-alpine as dev
ENV NODE_ENV=development
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
EXPOSE 5000
CMD ["npm", "run", "dev"]

# build
FROM node:22-alpine as build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build
# Debugging step to list contents of /app to verify /app/dist exists
RUN ls -l /app



# Production specific setup
FROM node:22-alpine as prod
WORKDIR /app
COPY --from=build /app/dist dist
EXPOSE 5000
CMD ["npm", "run", "start"]

